language: php

services:
#  - mysql
#  - memcached
#  - redis

php:
  - 7.0
  - 7.1
  
before_script:
  - if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then pecl install mailparse; fi
  - echo 'upload_tmp_dir = "/tmp"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script:
  - composer install --no-dev
  - cd tests/
  - composer install
  - vendor/bin/phpunit -c phpunit.cerb.platform.xml
